version: "2.1"
services:
  mysqldatabase:
   container_name: mysql-database
   image: mysql:latest
   environment:
    MYSQL_DATABASE: mysqldb
    MYSQL_ROOT_PASSWORD: password@123
    MYSQL_ROOT_HOST: '%'
    MYSQL_USER: sa
    MYSQL_PASSWORD: password@321
   ports: 
   - "3306:3306"
   restart: always
   healthcheck:
    test: mysqladmin -uroot -ppassword@123 ping
    interval: 2s
    timeout: 5s
    retries: 30     
   
  student-info-service:
   restart: always 
   container_name: student-info
   image: student-info:latest
   depends_on: 
    mysqldatabase: 
                 condition: service_healthy    
   ports: 
    - 8080:8181
   environment: 
    spring.datasource.url: jdbc:mysql://mysqldatabase:3306/mysqldb?useSSL=false
    spring.datasource.username: root
    spring.datasource.password: password@123
